<?php

namespace Kumi\Norikumi\Support;

use Kumi\Jinzai\Support\DefaultRoles as JinzaiDefaultRoles;
use Kumi\Kyoka\Support\DefaultRoles as BaseDefaultRoles;

class DefaultAccess
{
    protected static array $access = [
        BaseDefaultRoles::ADMINISTRATOR => [
            DefaultPermissions::VIEW_ANY_CREWS,
            // DefaultPermissions::DELETE_ANY_CREWS,
            DefaultPermissions::CREATE_CREW,
            DefaultPermissions::VIEW_CREW,
            DefaultPermissions::UPDATE_CREW,
            // DefaultPermissions::DELETE_CREW,

            DefaultPermissions::VIEW_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::CREATE_CREW_ACTIVITY,
            DefaultPermissions::VIEW_CREW_ACTIVITY,
            // DefaultPermissions::UPDATE_CREW_ACTIVITY,
            // DefaultPermissions::DELETE_CREW_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_CREW_ACTIVITIES,
            DefaultPermissions::VIEW_CREW_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_DOCUMENTS,
            DefaultPermissions::DELETE_ANY_DOCUMENTS,
            DefaultPermissions::CREATE_DOCUMENT,
            DefaultPermissions::VIEW_DOCUMENT,
            DefaultPermissions::UPDATE_DOCUMENT,
            DefaultPermissions::DELETE_DOCUMENT,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_ASSIGNMENTS,
            DefaultPermissions::DELETE_ANY_ASSIGNMENTS,
            DefaultPermissions::CREATE_ASSIGNMENT,
            DefaultPermissions::VIEW_ASSIGNMENT,
            DefaultPermissions::UPDATE_ASSIGNMENT,
            DefaultPermissions::DELETE_ASSIGNMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_REGISTRATION_FORM_ENTRIES,
            // DefaultPermissions::DELETE_ANY_REGISTRATION_FORM_ENTRIES,
            DefaultPermissions::CREATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::VIEW_REGISTRATION_FORM_ENTRY,
            // DefaultPermissions::UPDATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::DELETE_REGISTRATION_FORM_ENTRY,

            DefaultPermissions::VIEW_ANY_BANKS,
            DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_PAYOUT_ITEM,
            DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_DEPOSIT_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_DEPOSIT_PAYOUT_ITEM,
            DefaultPermissions::DELETE_DEPOSIT_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            DefaultPermissions::DELETE_LOAN,

            DefaultPermissions::APPROVE_LOAN,

            DefaultPermissions::VIEW_ANY_DEPOSITS,
            // DefaultPermissions::DELETE_ANY_DEPOSITS,
            DefaultPermissions::CREATE_DEPOSIT,
            // DefaultPermissions::VIEW_DEPOSIT,
            // DefaultPermissions::UPDATE_DEPOSIT,
            DefaultPermissions::DELETE_DEPOSIT,

            DefaultPermissions::APPROVE_DEPOSIT,
        ],

        JinzaiDefaultRoles::HUMAN_CAPITAL_MANAGER => [
            DefaultPermissions::VIEW_ANY_CREWS,
            // DefaultPermissions::DELETE_ANY_CREWS,
            DefaultPermissions::CREATE_CREW,
            DefaultPermissions::VIEW_CREW,
            DefaultPermissions::UPDATE_CREW,
            // DefaultPermissions::DELETE_CREW,

            DefaultPermissions::VIEW_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::CREATE_CREW_ACTIVITY,
            DefaultPermissions::VIEW_CREW_ACTIVITY,
            // DefaultPermissions::UPDATE_CREW_ACTIVITY,
            // DefaultPermissions::DELETE_CREW_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_CREW_ACTIVITIES,
            DefaultPermissions::VIEW_CREW_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_DOCUMENTS,
            DefaultPermissions::DELETE_ANY_DOCUMENTS,
            DefaultPermissions::CREATE_DOCUMENT,
            DefaultPermissions::VIEW_DOCUMENT,
            DefaultPermissions::UPDATE_DOCUMENT,
            DefaultPermissions::DELETE_DOCUMENT,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_ASSIGNMENTS,
            DefaultPermissions::DELETE_ANY_ASSIGNMENTS,
            DefaultPermissions::CREATE_ASSIGNMENT,
            DefaultPermissions::VIEW_ASSIGNMENT,
            DefaultPermissions::UPDATE_ASSIGNMENT,
            DefaultPermissions::DELETE_ASSIGNMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_REGISTRATION_FORM_ENTRIES,
            // DefaultPermissions::DELETE_ANY_REGISTRATION_FORM_ENTRIES,
            DefaultPermissions::CREATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::VIEW_REGISTRATION_FORM_ENTRY,
            // DefaultPermissions::UPDATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::DELETE_REGISTRATION_FORM_ENTRY,

            DefaultPermissions::VIEW_ANY_BANKS,
            DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_PAYOUT_ITEM,
            DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_DEPOSIT_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_DEPOSIT_PAYOUT_ITEM,
            DefaultPermissions::DELETE_DEPOSIT_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,

            DefaultPermissions::VIEW_ANY_DEPOSITS,
            // DefaultPermissions::DELETE_ANY_DEPOSITS,
            DefaultPermissions::CREATE_DEPOSIT,
            // DefaultPermissions::VIEW_DEPOSIT,
            // DefaultPermissions::UPDATE_DEPOSIT,
            // DefaultPermissions::DELETE_DEPOSIT,

            DefaultPermissions::APPROVE_DEPOSIT,
        ],

        DefaultRoles::CREWING_MANAGER => [
            DefaultPermissions::VIEW_ANY_CREWS,
            // DefaultPermissions::DELETE_ANY_CREWS,
            DefaultPermissions::CREATE_CREW,
            DefaultPermissions::VIEW_CREW,
            DefaultPermissions::UPDATE_CREW,
            // DefaultPermissions::DELETE_CREW,

            DefaultPermissions::VIEW_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::CREATE_CREW_ACTIVITY,
            DefaultPermissions::VIEW_CREW_ACTIVITY,
            // DefaultPermissions::UPDATE_CREW_ACTIVITY,
            // DefaultPermissions::DELETE_CREW_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_CREW_ACTIVITIES,
            DefaultPermissions::VIEW_CREW_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_DOCUMENTS,
            DefaultPermissions::DELETE_ANY_DOCUMENTS,
            DefaultPermissions::CREATE_DOCUMENT,
            DefaultPermissions::VIEW_DOCUMENT,
            DefaultPermissions::UPDATE_DOCUMENT,
            DefaultPermissions::DELETE_DOCUMENT,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_ASSIGNMENTS,
            DefaultPermissions::DELETE_ANY_ASSIGNMENTS,
            DefaultPermissions::CREATE_ASSIGNMENT,
            DefaultPermissions::VIEW_ASSIGNMENT,
            DefaultPermissions::UPDATE_ASSIGNMENT,
            DefaultPermissions::DELETE_ASSIGNMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_REGISTRATION_FORM_ENTRIES,
            // DefaultPermissions::DELETE_ANY_REGISTRATION_FORM_ENTRIES,
            DefaultPermissions::CREATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::VIEW_REGISTRATION_FORM_ENTRY,
            // DefaultPermissions::UPDATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::DELETE_REGISTRATION_FORM_ENTRY,

            DefaultPermissions::VIEW_ANY_BANKS,
            DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_PAYOUT_ITEM,
            DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_DEPOSIT_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_DEPOSIT_PAYOUT_ITEM,
            DefaultPermissions::DELETE_DEPOSIT_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,

            DefaultPermissions::VIEW_ANY_DEPOSITS,
            // DefaultPermissions::DELETE_ANY_DEPOSITS,
            DefaultPermissions::CREATE_DEPOSIT,
            // DefaultPermissions::VIEW_DEPOSIT,
            // DefaultPermissions::UPDATE_DEPOSIT,
            // DefaultPermissions::DELETE_DEPOSIT,

            DefaultPermissions::APPROVE_DEPOSIT,
        ],

        DefaultRoles::CREWING_ASSISTANT => [
            DefaultPermissions::VIEW_ANY_CREWS,
            // DefaultPermissions::DELETE_ANY_CREWS,
            DefaultPermissions::CREATE_CREW,
            DefaultPermissions::VIEW_CREW,
            DefaultPermissions::UPDATE_CREW,
            // DefaultPermissions::DELETE_CREW,

            // DefaultPermissions::VIEW_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::CREATE_CREW_ACTIVITY,
            DefaultPermissions::VIEW_CREW_ACTIVITY,
            // DefaultPermissions::UPDATE_CREW_ACTIVITY,
            // DefaultPermissions::DELETE_CREW_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_CREW_ACTIVITIES,
            // DefaultPermissions::VIEW_CREW_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_DOCUMENTS,
            // DefaultPermissions::DELETE_ANY_DOCUMENTS,
            DefaultPermissions::CREATE_DOCUMENT,
            DefaultPermissions::VIEW_DOCUMENT,
            DefaultPermissions::UPDATE_DOCUMENT,
            // DefaultPermissions::DELETE_DOCUMENT,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_ASSIGNMENTS,
            // DefaultPermissions::DELETE_ANY_ASSIGNMENTS,
            DefaultPermissions::CREATE_ASSIGNMENT,
            DefaultPermissions::VIEW_ASSIGNMENT,
            DefaultPermissions::UPDATE_ASSIGNMENT,
            // DefaultPermissions::DELETE_ASSIGNMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_REGISTRATION_FORM_ENTRIES,
            // DefaultPermissions::DELETE_ANY_REGISTRATION_FORM_ENTRIES,
            DefaultPermissions::CREATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::VIEW_REGISTRATION_FORM_ENTRY,
            // DefaultPermissions::UPDATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::DELETE_REGISTRATION_FORM_ENTRY,

            DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            // DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_DEPOSIT_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,

            DefaultPermissions::VIEW_ANY_DEPOSITS,
            // DefaultPermissions::DELETE_ANY_DEPOSITS,
            DefaultPermissions::CREATE_DEPOSIT,
            DefaultPermissions::VIEW_DEPOSIT,
            // DefaultPermissions::UPDATE_DEPOSIT,
            // DefaultPermissions::DELETE_DEPOSIT,

            DefaultPermissions::APPROVE_DEPOSIT,
        ],

        DefaultRoles::CREWING_USER => [
            DefaultPermissions::VIEW_ANY_CREWS,
            // DefaultPermissions::DELETE_ANY_CREWS,
            DefaultPermissions::CREATE_CREW,
            DefaultPermissions::VIEW_CREW,
            DefaultPermissions::UPDATE_CREW,
            // DefaultPermissions::DELETE_CREW,

            // DefaultPermissions::VIEW_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_CREW_ACTIVITIES,
            // DefaultPermissions::CREATE_CREW_ACTIVITY,
            DefaultPermissions::VIEW_CREW_ACTIVITY,
            // DefaultPermissions::UPDATE_CREW_ACTIVITY,
            // DefaultPermissions::DELETE_CREW_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_CREW_ACTIVITIES,
            // DefaultPermissions::VIEW_CREW_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_DOCUMENTS,
            // DefaultPermissions::DELETE_ANY_DOCUMENTS,
            DefaultPermissions::CREATE_DOCUMENT,
            DefaultPermissions::VIEW_DOCUMENT,
            DefaultPermissions::UPDATE_DOCUMENT,
            // DefaultPermissions::DELETE_DOCUMENT,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_ASSIGNMENTS,
            // DefaultPermissions::DELETE_ANY_ASSIGNMENTS,
            DefaultPermissions::CREATE_ASSIGNMENT,
            DefaultPermissions::VIEW_ASSIGNMENT,
            DefaultPermissions::UPDATE_ASSIGNMENT,
            // DefaultPermissions::DELETE_ASSIGNMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            // DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            // DefaultPermissions::CREATE_PAYROLL,
            // DefaultPermissions::VIEW_PAYROLL,
            // DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_REGISTRATION_FORM_ENTRIES,
            // DefaultPermissions::DELETE_ANY_REGISTRATION_FORM_ENTRIES,
            DefaultPermissions::CREATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::VIEW_REGISTRATION_FORM_ENTRY,
            // DefaultPermissions::UPDATE_REGISTRATION_FORM_ENTRY,
            DefaultPermissions::DELETE_REGISTRATION_FORM_ENTRY,

            DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            // DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            // DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            // DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_DEPOSIT_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_DEPOSIT_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_DEPOSIT_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,

            // DefaultPermissions::VIEW_ANY_DEPOSITS,
            // DefaultPermissions::DELETE_ANY_DEPOSITS,
            // DefaultPermissions::CREATE_DEPOSIT,
            // DefaultPermissions::VIEW_DEPOSIT,
            // DefaultPermissions::UPDATE_DEPOSIT,
            // DefaultPermissions::DELETE_DEPOSIT,

            // DefaultPermissions::APPROVE_DEPOSIT,
        ],
    ];

    public static function getAccess(): array
    {
        return self::$access;
    }
}
