<?php

namespace Kumi\Jinzai\Support;

use Kumi\Kanri\Support\DefaultRoles as KanriDefaultRoles;
use Kumi\Kyoka\Support\DefaultRoles as BaseDefaultRoles;

class DefaultAccess
{
    protected static array $access = [
        BaseDefaultRoles::ADMINISTRATOR => [
            DefaultPermissions::OVERVIEW_JINZAI,

            DefaultPermissions::VIEW_ANY_EMPLOYEES,
            DefaultPermissions::DELETE_ANY_EMPLOYEES,
            DefaultPermissions::CREATE_EMPLOYEE,
            DefaultPermissions::VIEW_EMPLOYEE,
            DefaultPermissions::UPDATE_EMPLOYEE,
            DefaultPermissions::DELETE_EMPLOYEE,

            DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            DefaultPermissions::CREATE_DEPARTMENT,
            DefaultPermissions::VIEW_DEPARTMENT,
            DefaultPermissions::UPDATE_DEPARTMENT,
            DefaultPermissions::DELETE_DEPARTMENT,

            DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            DefaultPermissions::CREATE_JOB_POSITION,
            DefaultPermissions::VIEW_JOB_POSITION,
            DefaultPermissions::UPDATE_JOB_POSITION,
            DefaultPermissions::DELETE_JOB_POSITION,

            DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            DefaultPermissions::CREATE_EMPLOYMENT,
            DefaultPermissions::VIEW_EMPLOYMENT,
            DefaultPermissions::UPDATE_EMPLOYMENT,
            DefaultPermissions::DELETE_EMPLOYMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_BANKS,
            DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_PAYOUT_ITEM,
            DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            DefaultPermissions::DELETE_LOAN,

            DefaultPermissions::APPROVE_LOAN,
        ],

        KanriDefaultRoles::MANAGING_DIRECTOR => [
            // DefaultPermissions::OVERVIEW_JINZAI,

            // DefaultPermissions::VIEW_ANY_EMPLOYEES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEES,
            // DefaultPermissions::CREATE_EMPLOYEE,
            // DefaultPermissions::VIEW_EMPLOYEE,
            // DefaultPermissions::UPDATE_EMPLOYEE,
            // DefaultPermissions::DELETE_EMPLOYEE,

            // DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            // DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            // DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            // DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            // DefaultPermissions::CREATE_IDENTITY,
            // DefaultPermissions::VIEW_IDENTITY,
            // DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            // DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            // DefaultPermissions::CREATE_ADDRESS,
            // DefaultPermissions::VIEW_ADDRESS,
            // DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            // DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            // DefaultPermissions::CREATE_RELATIVE,
            // DefaultPermissions::VIEW_RELATIVE,
            // DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            // DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            // DefaultPermissions::CREATE_DEPARTMENT,
            // DefaultPermissions::VIEW_DEPARTMENT,
            // DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            // DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            // DefaultPermissions::CREATE_JOB_POSITION,
            // DefaultPermissions::VIEW_JOB_POSITION,
            // DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            // DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            // DefaultPermissions::CREATE_EMPLOYMENT,
            // DefaultPermissions::VIEW_EMPLOYMENT,
            // DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            // DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            // DefaultPermissions::CREATE_CONTRACT,
            // DefaultPermissions::VIEW_CONTRACT,
            // DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            // DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            // DefaultPermissions::CREATE_PAYROLL,
            // DefaultPermissions::VIEW_PAYROLL,
            // DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            // DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            // DefaultPermissions::CREATE_BANK,
            // DefaultPermissions::VIEW_BANK,
            // DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            DefaultPermissions::APPROVE_LOAN,
        ],

        KanriDefaultRoles::VICE_MANAGING_DIRECTOR => [
            // DefaultPermissions::OVERVIEW_JINZAI,

            // DefaultPermissions::VIEW_ANY_EMPLOYEES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEES,
            // DefaultPermissions::CREATE_EMPLOYEE,
            // DefaultPermissions::VIEW_EMPLOYEE,
            // DefaultPermissions::UPDATE_EMPLOYEE,
            // DefaultPermissions::DELETE_EMPLOYEE,

            // DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            // DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            // DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            // DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            // DefaultPermissions::CREATE_IDENTITY,
            // DefaultPermissions::VIEW_IDENTITY,
            // DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            // DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            // DefaultPermissions::CREATE_ADDRESS,
            // DefaultPermissions::VIEW_ADDRESS,
            // DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            // DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            // DefaultPermissions::CREATE_RELATIVE,
            // DefaultPermissions::VIEW_RELATIVE,
            // DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            // DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            // DefaultPermissions::CREATE_DEPARTMENT,
            // DefaultPermissions::VIEW_DEPARTMENT,
            // DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            // DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            // DefaultPermissions::CREATE_JOB_POSITION,
            // DefaultPermissions::VIEW_JOB_POSITION,
            // DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            // DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            // DefaultPermissions::CREATE_EMPLOYMENT,
            // DefaultPermissions::VIEW_EMPLOYMENT,
            // DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            // DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            // DefaultPermissions::CREATE_CONTRACT,
            // DefaultPermissions::VIEW_CONTRACT,
            // DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            // DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            // DefaultPermissions::CREATE_PAYROLL,
            // DefaultPermissions::VIEW_PAYROLL,
            // DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            // DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            // DefaultPermissions::CREATE_BANK,
            // DefaultPermissions::VIEW_BANK,
            // DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            DefaultPermissions::APPROVE_LOAN,
        ],

        DefaultRoles::HUMAN_CAPITAL_MANAGER => [
            DefaultPermissions::OVERVIEW_JINZAI,

            DefaultPermissions::VIEW_ANY_EMPLOYEES,
            DefaultPermissions::DELETE_ANY_EMPLOYEES,
            DefaultPermissions::CREATE_EMPLOYEE,
            DefaultPermissions::VIEW_EMPLOYEE,
            DefaultPermissions::UPDATE_EMPLOYEE,
            DefaultPermissions::DELETE_EMPLOYEE,

            DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            DefaultPermissions::CREATE_DEPARTMENT,
            DefaultPermissions::VIEW_DEPARTMENT,
            DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            DefaultPermissions::CREATE_JOB_POSITION,
            DefaultPermissions::VIEW_JOB_POSITION,
            DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            DefaultPermissions::CREATE_EMPLOYMENT,
            DefaultPermissions::VIEW_EMPLOYMENT,
            DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            DefaultPermissions::ACTIVATE_PAYROLL,

            DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY_DETAILS,

            DefaultPermissions::VIEW_ANY_BANKS,
            DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            DefaultPermissions::DELETE_BANK,

            DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            DefaultPermissions::CREATE_PAYOUT_ITEM,
            DefaultPermissions::VIEW_PAYOUT_ITEM,
            DefaultPermissions::UPDATE_PAYOUT_ITEM,
            DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,
        ],

        DefaultRoles::HUMAN_CAPITAL_ASSISTANT => [
            DefaultPermissions::OVERVIEW_JINZAI,

            DefaultPermissions::VIEW_ANY_EMPLOYEES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEES,
            DefaultPermissions::CREATE_EMPLOYEE,
            DefaultPermissions::VIEW_EMPLOYEE,
            DefaultPermissions::UPDATE_EMPLOYEE,
            // DefaultPermissions::DELETE_EMPLOYEE,

            // DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            DefaultPermissions::CREATE_DEPARTMENT,
            DefaultPermissions::VIEW_DEPARTMENT,
            DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            DefaultPermissions::CREATE_JOB_POSITION,
            DefaultPermissions::VIEW_JOB_POSITION,
            DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            DefaultPermissions::CREATE_EMPLOYMENT,
            DefaultPermissions::VIEW_EMPLOYMENT,
            DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,

            DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            // DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            // DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            // DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,
        ],

        DefaultRoles::HUMAN_CAPITAL_USER => [
            DefaultPermissions::OVERVIEW_JINZAI,

            DefaultPermissions::VIEW_ANY_EMPLOYEES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEES,
            DefaultPermissions::CREATE_EMPLOYEE,
            DefaultPermissions::VIEW_EMPLOYEE,
            DefaultPermissions::UPDATE_EMPLOYEE,
            // DefaultPermissions::DELETE_EMPLOYEE,

            // DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            DefaultPermissions::CREATE_IDENTITY,
            DefaultPermissions::VIEW_IDENTITY,
            DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            DefaultPermissions::CREATE_ADDRESS,
            DefaultPermissions::VIEW_ADDRESS,
            DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            DefaultPermissions::CREATE_RELATIVE,
            DefaultPermissions::VIEW_RELATIVE,
            DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            DefaultPermissions::CREATE_DEPARTMENT,
            DefaultPermissions::VIEW_DEPARTMENT,
            DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            DefaultPermissions::CREATE_JOB_POSITION,
            DefaultPermissions::VIEW_JOB_POSITION,
            DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            DefaultPermissions::CREATE_EMPLOYMENT,
            DefaultPermissions::VIEW_EMPLOYMENT,
            DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            DefaultPermissions::CREATE_PAYROLL,
            DefaultPermissions::VIEW_PAYROLL,
            DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,

            DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            DefaultPermissions::CREATE_BANK,
            DefaultPermissions::VIEW_BANK,
            DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            // DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            // DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            // DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,
        ],

        DefaultRoles::LEGAL_OFFICER => [
            // DefaultPermissions::OVERVIEW_JINZAI,
            // DefaultPermissions::VIEW_ANY_EMPLOYEES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEES,
            // DefaultPermissions::CREATE_EMPLOYEE,
            // DefaultPermissions::VIEW_EMPLOYEE,
            // DefaultPermissions::UPDATE_EMPLOYEE,
            // DefaultPermissions::DELETE_EMPLOYEE,

            // DefaultPermissions::VIEW_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::CREATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::UPDATE_EMPLOYEE_ACTIVITY,
            // DefaultPermissions::DELETE_EMPLOYEE_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_EMPLOYEE_ACTIVITIES,
            // DefaultPermissions::VIEW_EMPLOYEE_ACTIVITY_DETAILS,

            // DefaultPermissions::CREATE_EMPLOYEE_ONBOARDING_LINK,
            // DefaultPermissions::VIEW_EMPLOYEE_ONBOARDING_LINK,

            // DefaultPermissions::VIEW_ANY_IDENTITIES,
            // DefaultPermissions::DELETE_ANY_IDENTITIES,
            // DefaultPermissions::CREATE_IDENTITY,
            // DefaultPermissions::VIEW_IDENTITY,
            // DefaultPermissions::UPDATE_IDENTITY,
            // DefaultPermissions::DELETE_IDENTITY,

            // DefaultPermissions::VIEW_ANY_ADDRESSES,
            // DefaultPermissions::DELETE_ANY_ADDRESSES,
            // DefaultPermissions::CREATE_ADDRESS,
            // DefaultPermissions::VIEW_ADDRESS,
            // DefaultPermissions::UPDATE_ADDRESS,
            // DefaultPermissions::DELETE_ADDRESS,

            // DefaultPermissions::VIEW_ANY_RELATIVES,
            // DefaultPermissions::DELETE_ANY_RELATIVES,
            // DefaultPermissions::CREATE_RELATIVE,
            // DefaultPermissions::VIEW_RELATIVE,
            // DefaultPermissions::UPDATE_RELATIVE,
            // DefaultPermissions::DELETE_RELATIVE,

            // DefaultPermissions::VIEW_ANY_DEPARTMENTS,
            // DefaultPermissions::DELETE_ANY_DEPARTMENTS,
            // DefaultPermissions::CREATE_DEPARTMENT,
            // DefaultPermissions::VIEW_DEPARTMENT,
            // DefaultPermissions::UPDATE_DEPARTMENT,
            // DefaultPermissions::DELETE_DEPARTMENT,

            // DefaultPermissions::VIEW_ANY_JOB_POSITIONS,
            // DefaultPermissions::DELETE_ANY_JOB_POSITIONS,
            // DefaultPermissions::CREATE_JOB_POSITION,
            // DefaultPermissions::VIEW_JOB_POSITION,
            // DefaultPermissions::UPDATE_JOB_POSITION,
            // DefaultPermissions::DELETE_JOB_POSITION,

            // DefaultPermissions::VIEW_JOB_POSITION_LEVEL,
            // DefaultPermissions::UPDATE_JOB_POSITION_LEVEL,

            // DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            // DefaultPermissions::CREATE_EMPLOYMENT,
            // DefaultPermissions::VIEW_EMPLOYMENT,
            // DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,
            // DefaultPermissions::VIEW_ANY_EMPLOYMENTS,
            // DefaultPermissions::DELETE_ANY_EMPLOYMENTS,
            // DefaultPermissions::CREATE_EMPLOYMENT,
            // DefaultPermissions::VIEW_EMPLOYMENT,
            // DefaultPermissions::UPDATE_EMPLOYMENT,
            // DefaultPermissions::DELETE_EMPLOYMENT,

            DefaultPermissions::VIEW_ANY_CONTRACTS,
            // DefaultPermissions::DELETE_ANY_CONTRACTS,
            // DefaultPermissions::CREATE_CONTRACT,
            DefaultPermissions::VIEW_CONTRACT,
            DefaultPermissions::UPDATE_CONTRACT,
            // DefaultPermissions::DELETE_CONTRACT,

            // DefaultPermissions::VIEW_ANY_PAYROLLS,
            // DefaultPermissions::DELETE_ANY_PAYROLLS,
            // DefaultPermissions::CREATE_PAYROLL,
            // DefaultPermissions::VIEW_PAYROLL,
            // DefaultPermissions::UPDATE_PAYROLL,
            // DefaultPermissions::DELETE_PAYROLL,

            // DefaultPermissions::MANAGE_PAYROLL_SALARY_DATA,
            // DefaultPermissions::ACTIVATE_ANY_PAYROLLS,
            // DefaultPermissions::ACTIVATE_PAYROLL,

            // DefaultPermissions::VIEW_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYROLL_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::VIEW_PAYROLL_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYROLL_ACTIVITY,
            // DefaultPermissions::DELETE_PAYROLL_ACTIVITY,

            // DefaultPermissions::VIEW_RECENT_PAYROLL_ACTIVITIES,

            // DefaultPermissions::VIEW_ANY_BANKS,
            // DefaultPermissions::DELETE_ANY_BANKS,
            // DefaultPermissions::CREATE_BANK,
            // DefaultPermissions::VIEW_BANK,
            // DefaultPermissions::UPDATE_BANK,
            // DefaultPermissions::DELETE_BANK,

            // DefaultPermissions::VIEW_ANY_PAYOUTS,
            // DefaultPermissions::DELETE_ANY_PAYOUTS,
            // DefaultPermissions::CREATE_PAYOUT,
            // DefaultPermissions::VIEW_PAYOUT,
            // DefaultPermissions::UPDATE_PAYOUT,
            // DefaultPermissions::DELETE_PAYOUT,

            // DefaultPermissions::APPROVE_ANY_PAYOUTS,
            // DefaultPermissions::DISBURSE_ANY_PAYOUTS,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ACTIVITIES,
            // DefaultPermissions::CREATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::VIEW_PAYOUT_ACTIVITY,
            // DefaultPermissions::UPDATE_PAYOUT_ACTIVITY,
            // DefaultPermissions::DELETE_PAYOUT_ACTIVITY,

            // DefaultPermissions::VIEW_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::DELETE_ANY_LOAN_PAYOUT_ITEMS,
            // DefaultPermissions::CREATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::VIEW_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::UPDATE_LOAN_PAYOUT_ITEM,
            // DefaultPermissions::DELETE_LOAN_PAYOUT_ITEM,

            // DefaultPermissions::VIEW_ANY_LOANS,
            // DefaultPermissions::DELETE_ANY_LOANS,
            // DefaultPermissions::CREATE_LOAN,
            // DefaultPermissions::VIEW_LOAN,
            // DefaultPermissions::UPDATE_LOAN,
            // DefaultPermissions::DELETE_LOAN,

            // DefaultPermissions::APPROVE_LOAN,
        ],
    ];

    public static function getAccess(): array
    {
        return self::$access;
    }
}
